title: "Suzhen Zhong"
email: suzhenxzhong@gmail.com
description: >- # this means to ignore newlines until next field
  Researcher in Software Engineering and AI. Canada Research Chair applicant.
url: "https://suzhenxzhong.github.io"
twitter_username: ""
github_username: suzhenxzhong
minimal_mistakes_skin: "default"
markdown: kramdown
# More config lines...
