author:
  # Biographic information
  avatar           : "/images/profile.png"          # put your photo in /images or /assets/img
  name             : "Suzhen Zhong"
  location         : "Kingston, Canada"
  employer         : "Queen’s University"
  email            : "suzhen.zhong@queensu.ca"

  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?user=<your_id>"
  orcid            : "https://orcid.org/0000-0000-0000-0000"

  # Repositories and software development
  github           : "https://github.com/suzhenxzhong"

  # Social media
  linkedin         : "https://www.linkedin.com/in/suzhen-zhong-09a62a236/"
